// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wztfuhaaklcnflszoefa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6dGZ1aGFha2xjbmZsc3pvZWZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjA0ODYsImV4cCI6MjA3MDU5NjQ4Nn0.q3SGKvredUbo_x0yoGQjp4dopZ-cpAGNAf7DJEcdhiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});